name: spendi-dev
services:
  db:
    container_name: dev-prisma
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
